"""
Business 3 — Shopify Store Manager (EdisonHaus)
Takes pending products from DB, lists them on Shopify.
Uses collection_id stored by product finder — no guessing, no off-theme products.
Runs via GitHub Actions 2x/week.
"""

import os, json, time, sqlite3, logging, requests
from datetime import datetime
from pathlib import Path
import anthropic

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger(__name__)

# ── Env ────────────────────────────────────────────────────────────────────────
SHOPIFY_STORE        = os.environ.get("SHOPIFY_STORE", "fgtyz6-bj.myshopify.com")
SHOPIFY_ACCESS_TOKEN = os.environ["SHOPIFY_ACCESS_TOKEN"]
LISTINGS_PER_RUN     = int(os.environ.get("LISTINGS_PER_RUN", "50"))
DB_PATH              = os.environ.get("DB_PATH", "data/dropship.db")
ANTHROPIC_API_KEY    = os.environ.get("ANTHROPIC_API_KEY", "")

Path("data").mkdir(exist_ok=True)
HEARTBEAT = Path("b3_store_heartbeat.json")

SHOPIFY_HEADERS = {
    "X-Shopify-Access-Token": SHOPIFY_ACCESS_TOKEN,
    "Content-Type": "application/json"
}
SHOPIFY_BASE = f"https://{SHOPIFY_STORE}/admin/api/2024-01"

FEATURED_COLLECTION_ID = 305042358346  # Updated for Pet Home Accessories

# ── Theme QA Gate (auto-generated by phase4_pipeline_lockdown) ──
THEME = "Pet Home Accessories"
THEME_COLLECTIONS = {
    "Feeding & Dining": 305042325578,
    "Comfort & Rest": 305042358346,
    "Play & Entertainment": 305042391114,
    "Storage & Organization": 305042423882,
    "Safety & Security": 305042456650,
    "Grooming & Care": 305042489418
}

def theme_check_product(client, product: dict) -> tuple:
    """Check if product fits theme before listing. Returns (passes, collection_name)."""
    title = product.get("title", "")
    description = product.get("ai_description", "")
    collections_list = list(THEME_COLLECTIONS.keys())

    prompt = f"""You are a product curator for EdisonHaus, a {THEME} store.

Product: {title}
Description: {description}

1. Does this product fit the "{THEME}" theme? Answer YES or NO.
2. If YES, which collection does it belong in? Options: {collections_list}

Return ONLY valid JSON: {"fit": true/false, "collection": "name or null", "reason": "one sentence"}"""

    try:
        msg = client.messages.create(
            model="claude-sonnet-4-20250514",
            max_tokens=150,
            messages=[{"role": "user", "content": prompt}]
        )
        raw = msg.content[0].text.strip().replace("```json", "").replace("```", "").strip()
        result = json.loads(raw)
        return result.get("fit", False), result.get("collection")
    except Exception as e:
        log.warning(f"Theme check failed: {e}")
        return True, None  # Default to pass on error



# ── DB ─────────────────────────────────────────────────────────────────────────
def init_db() -> sqlite3.Connection:
    conn = sqlite3.connect(DB_PATH)
    try:
        conn.execute("ALTER TABLE products ADD COLUMN shopify_id TEXT")
        conn.commit()
    except Exception:
        pass
    try:
        conn.execute("ALTER TABLE products ADD COLUMN collection_id INTEGER")
        conn.commit()
    except Exception:
        pass
    return conn

def get_pending_products(conn, limit: int) -> list:
    rows = conn.execute("""
        SELECT id, cj_id, title, niche, collection_id, cost_usd, sell_price,
               image_url, product_url, ai_description, ai_tags
        FROM products
        WHERE status = 'pending'
        ORDER BY ai_score DESC, created_at ASC
        LIMIT ?
    """, (limit,)).fetchall()
    return [dict(zip(
        ["id","cj_id","title","niche","collection_id","cost_usd","sell_price",
         "image_url","product_url","ai_description","ai_tags"], row
    )) for row in rows]

def mark_listed(conn, product_id: int, shopify_id: str):
    conn.execute(
        "UPDATE products SET status='listed', shopify_id=? WHERE id=?",
        (shopify_id, product_id)
    )
    conn.commit()

# ── Shopify ────────────────────────────────────────────────────────────────────
def create_shopify_product(product: dict) -> str | None:
    title = product["title"]
    if len(title) > 80:
        title = title[:77] + "..."

    body_html = f"<p>{product['ai_description']}</p>" if product.get("ai_description") else "<p>Premium quality home and lifestyle product.</p>"

    image_url = product.get("image_url", "")
    has_real_image = image_url and "4a4a4a" not in image_url and "placehold" not in image_url

    payload = {
        "product": {
            "title": title,
            "body_html": body_html,
            "vendor": "EdisonHaus",
            "product_type": product["niche"].title(),
            "tags": product.get("ai_tags", product["niche"]),
            "status": "active",
            "variants": [{
                "price": str(round(product["sell_price"], 2)),
                "compare_at_price": str(round(product["sell_price"] * 1.3, 2)),
                "inventory_management": None,
                "fulfillment_service": "manual",
                "requires_shipping": True,
                "taxable": True
            }],
            "images": [{"src": image_url}] if has_real_image else []
        }
    }

    for attempt in range(3):
        try:
            resp = requests.post(
                f"{SHOPIFY_BASE}/products.json",
                headers=SHOPIFY_HEADERS,
                json=payload,
                timeout=20
            )
            if resp.status_code == 201:
                shopify_id = str(resp.json()["product"]["id"])
                log.info(f"  Created: {title[:50]} → #{shopify_id}")

                # Assign to niche collection (stored by product finder)
                collection_id = product.get("collection_id")
                if collection_id:
                    add_to_collection(shopify_id, int(collection_id))

                # Always add to Featured collection
                add_to_collection(shopify_id, FEATURED_COLLECTION_ID)

                # Store CJ ID as metafield for order fulfiller
                if product.get("cj_id"):
                    add_metafield(shopify_id, product.get("product_url", ""), product["cj_id"])

                return shopify_id

            elif resp.status_code == 429:
                log.warning("Rate limited — waiting 10s")
                time.sleep(10)
            else:
                log.error(f"Shopify error {resp.status_code}: {resp.text[:200]}")
                return None

        except Exception as e:
            log.error(f"Request error attempt {attempt+1}: {e}")
            time.sleep(2 ** attempt)

    return None

def add_to_collection(shopify_product_id: str, collection_id: int):
    try:
        resp = requests.post(
            f"{SHOPIFY_BASE}/collects.json",
            headers=SHOPIFY_HEADERS,
            json={"collect": {"product_id": int(shopify_product_id), "collection_id": collection_id}},
            timeout=10
        )
        if resp.status_code in [200, 201]:
            log.info(f"    → Collection {collection_id} ✓")
        elif resp.status_code == 422:
            log.info(f"    → Collection {collection_id} (already assigned)")
        else:
            log.warning(f"    → Collection {collection_id} failed: {resp.status_code}")
    except Exception as e:
        log.warning(f"Collection add error: {e}")

def add_metafield(shopify_product_id: str, cj_url: str, cj_id: str):
    for key, value in [("cj_product_url", cj_url), ("cj_product_id", cj_id)]:
        try:
            requests.post(
                f"{SHOPIFY_BASE}/products/{shopify_product_id}/metafields.json",
                headers=SHOPIFY_HEADERS,
                json={"metafield": {
                    "namespace": "dropship",
                    "key": key,
                    "value": value,
                    "type": "single_line_text_field"
                }},
                timeout=10
            )
        except Exception as e:
            log.warning(f"Metafield error: {e}")

# ── Heartbeat ──────────────────────────────────────────────────────────────────
def write_heartbeat(listed: int, status: str = "success"):
    HEARTBEAT.write_text(json.dumps({
        "module": "b3_store_manager",
        "last_run": datetime.now().isoformat(),
        "listed": listed,
        "status": status
    }, indent=2))

# ── Main ───────────────────────────────────────────────────────────────────────
def main():
    log.info("=" * 60)
    log.info("B3 Store Manager — EdisonHaus")
    log.info("=" * 60)

    try:
        conn     = init_db()
        products = get_pending_products(conn, LISTINGS_PER_RUN)
        log.info(f"Listing {len(products)} products to {SHOPIFY_STORE}")

        if not products:
            log.info("No pending products. Run b3_product_finder.py first.")
            write_heartbeat(0, "no_products")
            return

        listed = 0
        skipped_theme = 0
        ai_client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY) if ANTHROPIC_API_KEY else None

        for product in products:
            # Theme QA gate — reject off-theme products before listing
            if ai_client:
                fits, suggested_collection = theme_check_product(ai_client, product)
                if not fits:
                    log.info(f"  ✗ Theme reject: {product['title'][:50]}")
                    conn.execute("UPDATE products SET status='theme_rejected' WHERE id=?", (product["id"],))
                    conn.commit()
                    skipped_theme += 1
                    continue
                # Override collection if AI suggests one
                if suggested_collection and suggested_collection in THEME_COLLECTIONS:
                    product["collection_id"] = THEME_COLLECTIONS[suggested_collection]

            shopify_id = create_shopify_product(product)
            if shopify_id:
                mark_listed(conn, product["id"], shopify_id)
                listed += 1
            time.sleep(0.6)

        log.info(f"Done. Listed {listed}/{len(products)} products. Theme-rejected: {skipped_theme}")
        write_heartbeat(listed)
        conn.close()

    except Exception as e:
        log.error(f"Store manager failed: {e}")
        write_heartbeat(0, status=f"error: {e}")
        raise

if __name__ == "__main__":
    main()
